# Generated by Django 4.2.2 on 2023-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_items')),
                ('label', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='new_comments')),
                ('status', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TopView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='top_views')),
                ('episode', models.CharField(max_length=10)),
                ('views', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('filter_day', models.BooleanField(default=False)),
                ('filter_week', models.BooleanField(default=False)),
                ('filter_month', models.BooleanField(default=False)),
                ('filter_years', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trending_products')),
                ('episode', models.CharField(max_length=10)),
                ('comments', models.IntegerField()),
                ('views', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
