# Generated by Django 4.2.2 on 2023-07-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_trendingproduct_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingproduct',
            old_name='image',
            new_name='image1',
        ),
    ]
