# Generated by Django 4.2.2 on 2023-07-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_image_trendingproduct_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topview',
            old_name='filter_years',
            new_name='filter_year',
        ),
        migrations.AlterModelTable(
            name='newcomment',
            table='tb_NewComment',
        ),
        migrations.AlterModelTable(
            name='topview',
            table='tb_TopView',
        ),
        migrations.AlterModelTable(
            name='trendingproduct',
            table='tb_TrendingProduct',
        ),
    ]
