# Generated by Django 4.2.2 on 2023-07-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_anime_resumen_remove_comment_blog_delete_blog_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anime',
            table='Animeblog.bd',
        ),
    ]
