# Generated by Django 4.2.2 on 2023-07-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='titulo',
        ),
    ]
