# Generated by Django 4.2.2 on 2023-07-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_description_video_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='imagen',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
