# Generated by Django 4.2.2 on 2023-07-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_video_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='imagen',
            old_name='imagen',
            new_name='imagen_2',
        ),
    ]
