# Generated by Django 4.2.2 on 2023-07-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime_todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagen_anime_todo')),
                ('capitulos', models.CharField(max_length=10)),
                ('comentarios', models.IntegerField()),
                ('views', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('vistas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='top_views')),
                ('capitulos', models.CharField(max_length=10)),
                ('vistas', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('Dia', models.BooleanField(default=False)),
                ('Semana', models.BooleanField(default=False)),
                ('Mes', models.BooleanField(default=False)),
                ('Años', models.BooleanField(default=False)),
            ],
        ),
    ]
