# Generated by Django 4.2.2 on 2023-07-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime_todo',
            old_name='vistas',
            new_name='nombre',
        ),
    ]
